config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, except: [:destroy, :edit, :update]

  root 'sessions#new'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  get '/dashboard/:id', to: "users#dashboard", as: "dashboard_user"

  delete '/logout', to: "sessions#destroy"
  resources :conversations do
    resources :messages
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: :User
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: :User

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?)
            OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
            sender_id,recipient_id, recipient_id, sender_id)
  end

end
#

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :name
  validates :email, presence: true, uniqueness: true

  has_many :conversations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
   redirect_to login_path unless current_user
 end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @users = User.all
    @converstaions = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id]), params[:recipient_id].first
    else
      @covnersation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  def show
    @conversation = Conversation.between()

  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/controllers/messages_controller.rb
class MessagesConroller < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:converastion_id])
  end

  def index
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Successful login"
      redirect_to dashboard_user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session.clear
    flash[:logout] = "Succesful Logout!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:dashboard]

  def index
    @users = User.all

  end

  def new
    @user = User.new
  end

  def dashboard
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Successful login"
      redirect_to dashboard_user_path(@user)
    else
      render :new
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobotMatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
       <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %>
    prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end  %>
    </ul>
<% end %>

app/views/users/dashboard.html.erb
<h1>Welcome <%= @user.name %></h1>
<%= link_to "Logout", logout_path, method: :delete %>

app/views/users/index.html.erb
<h1>Chat up your match!</h1>

<h3>membership:</h3>

<% @users.each do |recipient| %>
  <% if recipient.id != current_user.id %>
    <%=link_to "message #{recipient.name}",
                              conversation_path(sender_id: current_user.id,
                              recipient_id: recipient.id),
                              method: 'post' %>
                            </br>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="card">
    <div class="card-block">

      <h2 align="center">Create your Robot Account</h2>

      <%= form_for @user do |f| %>
        <div class="row">
          <div class="col-md-3"></div>

            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :name %></br>
                <%= f.text_field :name, class: "form-control"  %>
              </div>

              <div class="form-group">
                <%= f.label :email %></br>
                <%= f.text_field :email, class: "form-control"  %>
              </div>

              <div class="form-group">
                <%= f.label :password %></br>
                <%= f.password_field :password, class: "form-control"  %>
              </div>

              <div class="form-group">
                <%= f.submit "Create Account", class: "btn btn-primary btn-lg btn-block" %>
              </div>
            </div>
          </div>

        <div class="col-md-3"></div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
welcome